apiVersion: v1
kind: Pod
metadata:
  name: content-pod-1
  labels:
    app: server_app
spec:
  containers:
    - name: server-c-1
      image: suneha/my-content-ubserver:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: nfsvol 
          mountPath: /var/nfsshare
      securityContext:
         privileged: true
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "cp /var/nfsshare/install_server.sh /root; /var/nfsshare/install_server.sh; while true; do sleep 30; done;" ]
  volumes:
    - name: nfsvol
      persistentVolumeClaim:
        claimName: nfs-pvc

