apiVersion: v1
kind: Service
metadata:
  name: chef-server-1
  labels:
    app: chef-server-service-1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8170
    protocol: TCP
  selector:
    app: chef
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chef-server-deployment-1
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: chef
  template:
    metadata:
      labels:
        app: chef
    spec:
      containers:
        - name: server-c-1
          image: suneha/my-content-ubserver:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: nfsvol
              mountPath: /var/nfsshare
          securityContext:
             privileged: true
          command: [ "/bin/bash", "-c", "--" ]
          ports:
            - containerPort: 80
      volumes:
        - name: nfsvol
          persistentVolumeClaim:
            claimName: nfs-pvc
