apiVersion: v1
kind: Pod
metadata:
  name: content-pod-1
  labels:
    app: server_app
spec:
  containers:
    - name: server-c-1
      image: suneha/my-content-ubserver:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: nfsvol
          mountPath: /var/nfsshare
      securityContext:
         privileged: true
      command: [ "/bin/bash" ]
    - args:
      - /server
      readinessProbe:
       exec:
        command:
         - /bin/sh
          - /var/nfsshare/install_server.sh
       initialDelaySeconds: 30
       periodSeconds: 5
  volumes:
    - name: nfsvol
      persistentVolumeClaim:
        claimName: nfs-pvc

