apiVersion: v1
kind: Pod
metadata:
  name: content-pod-1
  labels:
    app: server_app
spec:
  containers:
    - name: server-c-1
      image: suneha/my-content-server:latest
      imagePullPolicy: Always
      securityContext: 
         privileged: true
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
  imagePullSecrets:
    - name: regcred
