apiVersion: v1
kind: Pod
metadata:
  name: content-repo-pod
  labels:
    app: server_app
spec:
  containers:
    - name: repo
      image: suneha/my-repo:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: nfsvol
          mountPath: /var/nfsshare
      securityContext:
         privileged: true
      command: [ "/bin/bash" ]
      args: [ "/var/nfsshare/install_server.sh" ]
  volumes:
    - name: nfsvol
      persistentVolumeClaim:
        claimName: nfs-pvc

