apiVersion: v1
kind: Service
metadata:
  name: repo-server
  labels:
    app: repo-server-service
spec:
  type: NodePort
  ports:
  - port: 8786
    targetPort: 80
    protocol: TCP
  selector:
    app: repo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repo
  template:
    metadata:
      labels:
        app: repo
    spec:
      containers:
        - name: server-r-1
          image: suneha/my-repo:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: nfsvol
              mountPath: /var/nfsshare
          securityContext:
             privileged: true
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "systemctl enable httpd; while true; do sleep 30; done;" ]
          ports:
            - containerPort: 80
      volumes:
        - name: nfsvol
          persistentVolumeClaim:
            claimName: nfs-pvc

