apiVersion: v1
kind: Service
metadata:
  name: repo-server 
  labels:
    app: repo-server-service
spec:
  type: NodePort
  ports:
  - port: 8170
    targetPort: 80
    protocol: TCP
  selector:
    app: repo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-server-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: repo 
  template:
    metadata:
      labels:
        app: repo 
    spec:
      containers:
        - name: server-c-2
          image: suneha/my-content-ubserver:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: nfsvol
              mountPath: /var/nfsshare
          securityContext:
             privileged: true
          command: [ "/bin/bash" ]
          args: [ "/var/nfsshare/install_apache.sh" ]
          ports:
            - containerPort: 80
      volumes:
        - name: nfsvol
          persistentVolumeClaim:
            claimName: nfs-pvc
