apiVersion: v1
kind: Pod
metadata:
  name: repo
  labels:
    app: server_app1111
spec:
  containers:
    - name: repo
      image: suneha/my-repo:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      securityContext:
         allowPrivilegeEscalation: false
      command: [ "/bin/bash", "-c", "--"]
      args: [ " systemctl enable httpd; while true; do sleep 30; done;" ]

