apiVersion: v1
kind: Pod
metadata:
  name: content-pod-4
  labels:
    app: workstation_app
spec:
  containers:
    - name: container2
      image: suneha/my-content-ubserver:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: nfsvol 
          mountPath: /var/nfsshare
      securityContext:
         privileged: true
      command: [ "/bin/bash" ]
  volumes:
    - name: nfsvol
      persistentVolumeClaim:
        claimName: nfs-pvc

